var graph_coords = [
  //ул. Центральная
  streets['Центральная'],
  [houses[0].coords, wells[0].coords],
  [houses[1].coords, wells[1].coords],
  [houses[2].coords, wells[1].coords],
  [houses[3].coords, wells[1].coords],
  [houses[4].coords, wells[2].coords],
  [houses[5].coords, wells[2].coords],
  [houses[6].coords, wells[3].coords],
  [houses[7].coords, wells[4].coords],
  [houses[8].coords, wells[5].coords],
  [houses[9].coords, wells[5].coords],
  [houses[10].coords, wells[5].coords],
  [houses[11].coords, wells[6].coords],
  [houses[12].coords, wells[6].coords],
  [houses[13].coords, wells[6].coords],
  [houses[14].coords, wells[8].coords],
  [houses[15].coords, wells[9].coords],
  [houses[16].coords, wells[10].coords],
  [houses[17].coords, wells[11].coords],
  [houses[18].coords, wells[12].coords],
  [houses[19].coords, wells[13].coords],
  [houses[20].coords, wells[14].coords],
  //ул. Широкая
  streets['Широкая'],
  [houses[22].coords, wells[15].coords],
  [houses[23].coords, wells[15].coords],
  [houses[24].coords, wells[16].coords],
  [houses[25].coords, wells[16].coords],
  //ул. Школьная
  streets['Школьная'],
  [houses[26].coords, wells[17].coords],
  [houses[27].coords, wells[18].coords],
  [houses[28].coords, wells[20].coords],
  [houses[29].coords, wells[22].coords],
  [houses[30].coords, wells[22].coords],
  street_connectors,
];
